import { env } from "cloudflare:test";
import { OWNER_READ_SCOPE, ownerAuthoritySchema } from "@crewhelm/contracts";
import { describe, expect, it } from "vitest";
import * as z from "zod";

import { deriveOwnerKey } from "../owner/identity.js";
import { MCP_GETTING_STARTED_REFERENCE } from "./guidance.js";
import {
  MCP_PROGRESSIVE_OPERATION_SCHEMA_SIZE_BUDGET_BYTES,
  handleAuthenticatedMcpRequest,
} from "./server.js";

const origin = "https://crewhelm.test";
const toolListResponseSchema = z.looseObject({
  result: z.looseObject({
    tools: z.array(
      z.looseObject({
        annotations: z
          .looseObject({
            destructiveHint: z.boolean().optional(),
            idempotentHint: z.boolean().optional(),
            openWorldHint: z.boolean().optional(),
            readOnlyHint: z.boolean().optional(),
          })
          .optional(),
        description: z.string().optional(),
        inputSchema: z.record(z.string(), z.unknown()),
        name: z.string(),
        title: z.string().optional(),
      }),
    ),
  }),
});

type McpTool = z.infer<typeof toolListResponseSchema>["result"]["tools"][number];
type DocumentedOperation = {
  description: string;
  name: string;
  schema: Record<string, unknown>;
};
type DocumentedTool = { operations: DocumentedOperation[]; tool: McpTool };

const toolCallResponseSchema = z.looseObject({
  result: z.looseObject({
    content: z.array(z.looseObject({ text: z.string().optional(), type: z.string() })),
    isError: z.boolean(),
  }),
});
const operationListSchema = z.looseObject({
  ok: z.literal(true),
  operations: z.array(
    z.looseObject({
      description: z.string(),
      name: z.string(),
    }),
  ),
});
const operationSchemaResultSchema = z.looseObject({
  ok: z.literal(true),
  operation: z.string(),
  schema: z.record(z.string(), z.unknown()),
});

const GENERATED_NOTICE = "<!-- Generated by `pnpm docs:mcp`. Do not edit manually. -->";

function annotationLabels(tool: McpTool): string[] {
  const annotations = tool.annotations;

  if (!annotations) {
    return [];
  }

  return [
    annotations.readOnlyHint ? "read-only" : "write",
    annotations.destructiveHint ? "destructive" : "non-destructive",
    annotations.idempotentHint ? "idempotent" : "non-idempotent",
    annotations.openWorldHint ? "open-world" : "closed-world",
  ];
}

function schemaObject(value: unknown): Record<string, unknown> | null {
  const parsed = z.record(z.string(), z.unknown()).safeParse(value);
  return parsed.success ? parsed.data : null;
}

function schemaType(schema: Record<string, unknown>): string {
  if (typeof schema.$ref === "string") {
    return schema.$ref.split("/").at(-1) ?? "referenced value";
  }

  if (Array.isArray(schema.enum)) {
    return schema.enum.map((value) => JSON.stringify(value)).join(" | ");
  }

  if (Array.isArray(schema.anyOf)) {
    return schema.anyOf
      .map(schemaObject)
      .filter((value): value is Record<string, unknown> => value !== null)
      .map(schemaType)
      .join(" | ");
  }

  if (schema.type === "array") {
    const items = schemaObject(schema.items);
    return items === null ? "array" : `array of ${schemaType(items)}`;
  }

  return typeof schema.type === "string" ? schema.type : "value";
}

function markdownText(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

function schemaDetails(schema: Record<string, unknown>): string {
  const details: string[] = [];
  if (typeof schema.description === "string") details.push(schema.description);

  const constraints: [string, unknown][] = [
    ["minimum", schema.minimum],
    ["exclusive minimum", schema.exclusiveMinimum],
    ["maximum", schema.maximum],
    ["exclusive maximum", schema.exclusiveMaximum],
    ["minimum length", schema.minLength],
    ["maximum length", schema.maxLength],
    ["minimum items", schema.minItems],
    ["maximum items", schema.maxItems],
    ["format", schema.format],
    ["pattern", schema.pattern],
    ["default", schema.default],
  ];
  const present = constraints
    .filter(([, value]) => value !== undefined)
    .map(([label, value]) => `${label}: \`${String(value)}\``);
  if (present.length > 0) details.push(present.join("; "));

  return markdownText(details.join(" ") || "—");
}

function renderSchemaTable(schema: Record<string, unknown>): string[] {
  const properties = schemaObject(schema.properties);
  if (properties === null || Object.keys(properties).length === 0) {
    return ["No input fields."];
  }

  const required = new Set(Array.isArray(schema.required) ? schema.required : []);
  const rows = Object.entries(properties).map(([name, value]) => {
    const property = schemaObject(value) ?? {};
    return `| \`${name}\` | ${required.has(name) ? "Yes" : "No"} | ${markdownText(schemaType(property))} | ${schemaDetails(property)} |`;
  });

  return ["| Input | Required | Type | Details |", "| --- | --- | --- | --- |", ...rows];
}

function renderTool({ operations, tool }: DocumentedTool): string {
  const lines = [`## \`${tool.name}\``, ""];

  if (tool.title) {
    lines.push(`**${tool.title}**`, "");
  }

  if (tool.description) {
    lines.push(tool.description, "");
  }

  const labels = annotationLabels(tool);
  if (labels.length > 0) {
    lines.push(`Attributes: ${labels.join(", ")}.`, "");
  }

  if (operations.length > 0) {
    lines.push(
      "How to use this tool:",
      "",
      '1. Send `{"request":"operations"}` to list its subtools.',
      '2. Send `{"request":"schema","name":"…"}` for one subtool’s exact inputs.',
      '3. Send `{"request":"execute","name":"…","input":{…}}` to run it.',
      "",
      "| Subtool | Purpose |",
      "| --- | --- |",
      ...operations.map(
        (operation) =>
          `| \`${operation.name}\` | ${markdownText(operation.description.match(/^.*?[.!?](?:\s|$)/)?.[0].trim() ?? operation.description)} |`,
      ),
    );
  } else {
    lines.push("Call this tool directly. It has no subtools.");
  }

  for (const operation of operations) {
    lines.push(
      "",
      `### \`${operation.name}\``,
      "",
      operation.description,
      "",
      ...renderSchemaTable(operation.schema),
    );
  }

  return lines.join("\n");
}

function renderReferenceBody(tools: DocumentedTool[], includeTitle: boolean): string {
  const sections = tools
    .toSorted((left, right) => left.tool.name.localeCompare(right.tool.name))
    .map(renderTool);

  return [
    ...(includeTitle ? ["# MCP tool reference", ""] : []),
    "This reference is generated from Crewhelm's authenticated MCP catalog and progressive operation schemas.",
    "Tool availability does not grant authority; every call is subject to the authenticated",
    "owner, approved OAuth scopes, and current control-plane policy.",
    "",
    MCP_GETTING_STARTED_REFERENCE,
    "",
    ...sections.flatMap((section) => [section, ""]),
  ].join("\n");
}

function renderRepositoryReference(tools: DocumentedTool[]): string {
  return [GENERATED_NOTICE, "", renderReferenceBody(tools, true)].join("\n");
}

function renderSiteReference(tools: DocumentedTool[]): string {
  return [
    "---",
    "title: MCP tool reference",
    "description: Exact generated inputs and annotations for Crewhelm's authenticated MCP tools.",
    "type: reference",
    "audience: mcp-client",
    "area: reference",
    "availability: available",
    "sources:",
    "  - apps/worker/src/mcp/documentation.test.ts",
    "  - apps/worker/src/mcp/server.ts",
    "tableOfContents: false",
    "---",
    "",
    GENERATED_NOTICE,
    "",
    renderReferenceBody(tools, false),
  ].join("\n");
}

function toolListRequest(): Request {
  return new Request(`${origin}/mcp`, {
    body: JSON.stringify({
      id: 1,
      jsonrpc: "2.0",
      method: "tools/list",
      params: {},
    }),
    headers: {
      accept: "application/json, text/event-stream",
      "content-type": "application/json",
      "mcp-protocol-version": "2025-11-25",
    },
    method: "POST",
  });
}

function toolCallRequest(id: number, name: string, args: Record<string, unknown>): Request {
  return new Request(`${origin}/mcp`, {
    body: JSON.stringify({
      id,
      jsonrpc: "2.0",
      method: "tools/call",
      params: { arguments: args, name },
    }),
    headers: {
      accept: "application/json, text/event-stream",
      "content-type": "application/json",
      "mcp-protocol-version": "2025-11-25",
    },
    method: "POST",
  });
}

async function callTool(
  authority: z.infer<typeof ownerAuthoritySchema>,
  id: number,
  name: string,
  args: Record<string, unknown>,
): Promise<unknown> {
  const response = await handleAuthenticatedMcpRequest(toolCallRequest(id, name, args), env, {
    authority,
  });
  const result = toolCallResponseSchema.parse(await response.json()).result;
  expect(result.isError).toBe(false);
  return JSON.parse(result.content[0]?.text ?? "null") as unknown;
}

async function discoverTools(
  authority: z.infer<typeof ownerAuthoritySchema>,
  tools: McpTool[],
): Promise<DocumentedTool[]> {
  let requestId = 2;
  const documented: DocumentedTool[] = [];

  for (const tool of tools) {
    if (tool.name === "crewhelm_status") {
      documented.push({ operations: [], tool });
      continue;
    }

    const listed = operationListSchema.parse(
      await callTool(authority, requestId++, tool.name, { request: "operations" }),
    );
    const operations: DocumentedOperation[] = [];
    for (const operation of listed.operations) {
      const described = operationSchemaResultSchema.parse(
        await callTool(authority, requestId++, tool.name, {
          name: operation.name,
          request: "schema",
        }),
      );
      const serializedSchema = JSON.stringify(described.schema);
      expect(serializedSchema).not.toContain('"$ref"');
      expect(serializedSchema).not.toContain('"$defs"');
      expect(
        new TextEncoder().encode(serializedSchema).byteLength,
        `${tool.name}.${operation.name} progressive schema bytes`,
      ).toBeLessThanOrEqual(MCP_PROGRESSIVE_OPERATION_SCHEMA_SIZE_BUDGET_BYTES);
      operations.push({
        description: operation.description,
        name: described.operation,
        schema: described.schema,
      });
    }
    documented.push({ operations, tool });
  }

  return documented;
}

describe("MCP documentation", () => {
  it("matches the authenticated tool catalog", async () => {
    const authority = ownerAuthoritySchema.parse({
      clientId: "mcp-documentation",
      ownerKey: await deriveOwnerKey({
        issuer: "https://github.com",
        subject: "mcp-documentation",
      }),
      scopes: [OWNER_READ_SCOPE],
    });
    const response = await handleAuthenticatedMcpRequest(toolListRequest(), env, { authority });
    const payload = toolListResponseSchema.parse(await response.json());
    const tools = await discoverTools(authority, payload.result.tools);
    const repositoryReference = renderRepositoryReference(tools);
    const siteReference = renderSiteReference(tools);

    await expect(repositoryReference).toMatchFileSnapshot(
      "../../../../docs/reference/mcp-tools.md",
    );
    await expect(siteReference).toMatchFileSnapshot(
      "../../../../apps/site/src/content/docs/docs/reference/mcp-tools.md",
    );
  });
});
