import { env } from "cloudflare:test";
import { OWNER_READ_SCOPE, ownerAuthoritySchema } from "@crewhelm/contracts";
import { describe, expect, it } from "vitest";
import * as z from "zod";

import { deriveOwnerKey } from "../owner/identity.js";
import { expectConstructibleAuthoringInputs, schemaObject } from "./facade-test-support.js";
import { FACADE_THEME_DEFINITIONS } from "./facade-definitions.js";
import { MCP_GETTING_STARTED_REFERENCE } from "./guidance.js";
import {
  MCP_PROGRESSIVE_OPERATION_SCHEMA_SIZE_BUDGET_BYTES,
  handleAuthenticatedMcpRequest,
} from "./server.js";

const origin = "https://crewhelm.test";
const toolListResponseSchema = z.looseObject({
  result: z.looseObject({
    tools: z.array(
      z.looseObject({
        annotations: z
          .looseObject({
            destructiveHint: z.boolean().optional(),
            idempotentHint: z.boolean().optional(),
            openWorldHint: z.boolean().optional(),
            readOnlyHint: z.boolean().optional(),
          })
          .optional(),
        description: z.string().optional(),
        inputSchema: z.record(z.string(), z.unknown()),
        name: z.string(),
        title: z.string().optional(),
      }),
    ),
  }),
});

type McpTool = z.infer<typeof toolListResponseSchema>["result"]["tools"][number];
type DocumentedOperation = {
  description: string;
  name: string;
  schema: Record<string, unknown>;
};
type DocumentedTool = { operations: DocumentedOperation[]; tool: McpTool };
type FacadeTheme = (typeof FACADE_THEME_DEFINITIONS)[number];

const toolCallResponseSchema = z.looseObject({
  result: z.looseObject({
    content: z.array(z.looseObject({ text: z.string().optional(), type: z.string() })),
    isError: z.boolean(),
  }),
});
const operationListSchema = z.looseObject({
  ok: z.literal(true),
  operations: z.array(
    z.looseObject({
      description: z.string(),
      name: z.string(),
    }),
  ),
});
const operationSchemaResultSchema = z.looseObject({
  ok: z.literal(true),
  operation: z.string(),
  schema: z.record(z.string(), z.unknown()),
});

const GENERATED_NOTICE = "<!-- Generated by `pnpm docs:mcp`. Do not edit manually. -->";

function annotationLabels(tool: McpTool): string[] {
  const annotations = tool.annotations;

  if (!annotations) {
    return [];
  }

  return [
    annotations.readOnlyHint ? "read-only" : "write",
    annotations.destructiveHint ? "destructive" : "non-destructive",
    annotations.idempotentHint ? "idempotent" : "non-idempotent",
    annotations.openWorldHint ? "open-world" : "closed-world",
  ];
}

function schemaType(schema: Record<string, unknown>): string {
  if (typeof schema.$ref === "string") {
    return schema.$ref.split("/").at(-1) ?? "referenced value";
  }

  if (Array.isArray(schema.enum)) {
    return schema.enum.map((value) => JSON.stringify(value)).join(" | ");
  }

  if (Array.isArray(schema.anyOf)) {
    return schema.anyOf
      .map(schemaObject)
      .filter((value): value is Record<string, unknown> => value !== null)
      .map(schemaType)
      .join(" | ");
  }

  if (schema.type === "array") {
    const items = schemaObject(schema.items);
    return items === null ? "array" : `array of ${schemaType(items)}`;
  }

  return typeof schema.type === "string" ? schema.type : "value";
}

function markdownText(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

function markdownCodeSpan(value: string): string {
  const longestDelimiter = Math.max(0, ...(value.match(/`+/g)?.map((run) => run.length) ?? []));
  const delimiter = "`".repeat(longestDelimiter + 1);

  return `${delimiter}${value}${delimiter}`;
}

function schemaDetails(schema: Record<string, unknown>): string {
  const details: string[] = [];
  if (typeof schema.description === "string") details.push(schema.description);

  const constraints: [string, unknown][] = [
    ["minimum", schema.minimum],
    ["exclusive minimum", schema.exclusiveMinimum],
    ["maximum", schema.maximum],
    ["exclusive maximum", schema.exclusiveMaximum],
    ["minimum length", schema.minLength],
    ["maximum length", schema.maxLength],
    ["minimum items", schema.minItems],
    ["maximum items", schema.maxItems],
    ["format", schema.format],
    ["pattern", schema.pattern],
    ["default", schema.default],
  ];
  const present = constraints
    .filter(([, value]) => value !== undefined)
    .map(([label, value]) => `${label}: ${markdownCodeSpan(String(value))}`);
  if (present.length > 0) details.push(present.join("; "));

  return markdownText(details.join(" ") || "—");
}

function renderSchemaTable(schema: Record<string, unknown>): string[] {
  const properties = schemaObject(schema.properties);
  if (properties === null || Object.keys(properties).length === 0) {
    return ["No input fields."];
  }

  const required = new Set(Array.isArray(schema.required) ? schema.required : []);
  const rows = Object.entries(properties).map(([name, value]) => {
    const property = schemaObject(value) ?? {};
    return `| \`${name}\` | ${required.has(name) ? "Yes" : "No"} | ${markdownText(schemaType(property))} | ${schemaDetails(property)} |`;
  });

  return ["| Input | Required | Type | Details |", "| --- | --- | --- | --- |", ...rows];
}

function renderJsonSchema(schema: Record<string, unknown>): string[] {
  return [
    "",
    "<details>",
    "<summary>View exact JSON Schema</summary>",
    "",
    "```json",
    JSON.stringify(schema, null, 2),
    "```",
    "",
    "</details>",
  ];
}

function renderTool({ operations, tool }: DocumentedTool, headingLevel = 2): string {
  const lines = [`${"#".repeat(headingLevel)} \`${tool.name}\``, ""];

  if (tool.title) {
    lines.push(`**${tool.title}**`, "");
  }

  if (tool.description) {
    lines.push(tool.description, "");
  }

  const labels = annotationLabels(tool);
  if (labels.length > 0) {
    lines.push(`Attributes: ${labels.join(", ")}.`, "");
  }

  if (operations.length > 0) {
    lines.push(
      "How to use this tool:",
      "",
      '1. Send `{"request":"operations"}` to list its subtools.',
      '2. Send `{"request":"schema","name":"…"}` for one subtool’s exact inputs.',
      '3. Send `{"request":"execute","name":"…","input":{…}}` to run it.',
      "",
      "| Subtool | Purpose |",
      "| --- | --- |",
      ...operations.map(
        (operation) =>
          `| \`${operation.name}\` | ${markdownText(operation.description.match(/^.*?[.!?](?:\s|$)/)?.[0].trim() ?? operation.description)} |`,
      ),
    );
  } else {
    lines.push("Call this tool directly. It has no subtools.");
  }

  for (const operation of operations) {
    lines.push(
      "",
      `${"#".repeat(headingLevel + 1)} \`${operation.name}\``,
      "",
      operation.description,
      "",
      ...renderSchemaTable(operation.schema),
      ...renderJsonSchema(operation.schema),
    );
  }

  return lines.join("\n");
}

function authorityBoundary(): string[] {
  return [
    "This reference is generated from Crewhelm's authenticated MCP catalog and progressive operation schemas.",
    "Tool availability does not grant authority; every call is subject to the authenticated",
    "owner, approved OAuth scopes, and current control-plane policy.",
  ];
}

function themeTools(theme: FacadeTheme, tools: DocumentedTool[]): DocumentedTool[] {
  const documentedByName = new Map(tools.map((tool) => [tool.tool.name, tool]));

  return theme.tools.map(({ name }) => {
    const documented = documentedByName.get(name);
    if (documented === undefined) throw new Error(`Missing documented facade tool: ${name}`);
    return documented;
  });
}

function toolNames(tools: DocumentedTool[]): string {
  return tools.map(({ tool }) => `\`${tool.name}\``).join("<br />") || "—";
}

function renderOverviewBody(
  tools: DocumentedTool[],
  themeLink: (theme: FacadeTheme) => string,
  includeTitle: boolean,
): string {
  const status = tools.find(({ tool }) => tool.name === "crewhelm_status");
  if (status === undefined) throw new Error("Missing Crewhelm status tool documentation.");

  const rows = FACADE_THEME_DEFINITIONS.map((theme) => {
    const documented = themeTools(theme, tools);
    const reads = documented.filter(({ tool }) => tool.annotations?.readOnlyHint === true);
    const writes = documented.filter(({ tool }) => tool.annotations?.readOnlyHint !== true);
    return `| [${theme.label}](${themeLink(theme)}) | ${theme.description} | ${toolNames(reads)} | ${toolNames(writes)} |`;
  });

  return [
    ...(includeTitle ? ["# MCP Reference", ""] : []),
    ...authorityBoundary(),
    "",
    "Choose a theme, then use its read tools to obtain exact coordinates before calling a write tool.",
    "Recipes has two write tools because installation and publication have separate authority flows.",
    "",
    "| Theme | Outcome | Read tools | Write tools |",
    "| --- | --- | --- | --- |",
    ...rows,
    "",
    MCP_GETTING_STARTED_REFERENCE,
    "",
    renderTool(status),
    "",
  ].join("\n");
}

function renderThemeBody(
  theme: FacadeTheme,
  tools: DocumentedTool[],
  includeTitle: boolean,
): string {
  const documented = themeTools(theme, tools);
  const reads = documented.filter(({ tool }) => tool.annotations?.readOnlyHint === true);
  const writes = documented.filter(({ tool }) => tool.annotations?.readOnlyHint !== true);
  const sections = [
    {
      description: "Inspect state and obtain exact references without changing it.",
      label: "Read tools",
      tools: reads,
    },
    {
      description: "Preview or perform bounded changes under the required owner authority.",
      label: "Write tools",
      tools: writes,
    },
  ];

  return [
    ...(includeTitle ? [`# MCP ${theme.label} reference`, ""] : []),
    theme.description,
    "",
    ...authorityBoundary(),
    "",
    ...sections.flatMap((section) => [
      `## ${section.label}`,
      "",
      section.description,
      "",
      ...section.tools.flatMap((tool) => [renderTool(tool, 3), ""]),
    ]),
  ].join("\n");
}

function renderRepositoryOverview(tools: DocumentedTool[]): string {
  return [
    GENERATED_NOTICE,
    "",
    renderOverviewBody(tools, (theme) => `./${theme.slug}.md`, true),
  ].join("\n");
}

function renderRepositoryTheme(theme: FacadeTheme, tools: DocumentedTool[]): string {
  return [GENERATED_NOTICE, "", renderThemeBody(theme, tools, true)].join("\n");
}

function siteFrontmatter(title: string, description: string): string[] {
  return [
    "---",
    `title: ${title}`,
    `description: ${description}`,
    "type: reference",
    "audience: mcp-client",
    "area: mcp",
    "availability: available",
    "sources:",
    "  - apps/worker/src/mcp/documentation.test.ts",
    "  - apps/worker/src/mcp/facade-definitions.ts",
    "  - apps/worker/src/mcp/server.ts",
    "tableOfContents: false",
    "---",
  ];
}

function renderSiteOverview(tools: DocumentedTool[]): string {
  return [
    ...siteFrontmatter(
      "MCP Reference",
      "Choose a Crewhelm MCP theme, then inspect its generated read and write tool contracts.",
    ),
    "",
    GENERATED_NOTICE,
    "",
    renderOverviewBody(tools, (theme) => `/docs/reference/mcp/${theme.slug}/`, false),
  ].join("\n");
}

function renderSiteTheme(theme: FacadeTheme, tools: DocumentedTool[]): string {
  return [
    ...siteFrontmatter(
      `MCP ${theme.label}`,
      `Generated read and write tool contracts for Crewhelm ${theme.label.toLowerCase()}.`,
    ),
    "",
    GENERATED_NOTICE,
    "",
    renderThemeBody(theme, tools, false),
  ].join("\n");
}

function toolListRequest(): Request {
  return new Request(`${origin}/mcp`, {
    body: JSON.stringify({
      id: 1,
      jsonrpc: "2.0",
      method: "tools/list",
      params: {},
    }),
    headers: {
      accept: "application/json, text/event-stream",
      "content-type": "application/json",
      "mcp-protocol-version": "2025-11-25",
    },
    method: "POST",
  });
}

function toolCallRequest(id: number, name: string, args: Record<string, unknown>): Request {
  return new Request(`${origin}/mcp`, {
    body: JSON.stringify({
      id,
      jsonrpc: "2.0",
      method: "tools/call",
      params: { arguments: args, name },
    }),
    headers: {
      accept: "application/json, text/event-stream",
      "content-type": "application/json",
      "mcp-protocol-version": "2025-11-25",
    },
    method: "POST",
  });
}

async function callTool(
  authority: z.infer<typeof ownerAuthoritySchema>,
  id: number,
  name: string,
  args: Record<string, unknown>,
): Promise<unknown> {
  const response = await handleAuthenticatedMcpRequest(toolCallRequest(id, name, args), env, {
    authority,
  });
  const result = toolCallResponseSchema.parse(await response.json()).result;
  expect(result.isError, `${name} ${JSON.stringify(args)}`).toBe(false);
  return JSON.parse(result.content[0]?.text ?? "null") as unknown;
}

async function discoverTools(
  authority: z.infer<typeof ownerAuthoritySchema>,
  tools: McpTool[],
): Promise<DocumentedTool[]> {
  let requestId = 2;
  const documented: DocumentedTool[] = [];
  const descriptionsByOperationName = new Map<string, Set<string>>();

  for (const tool of tools) {
    if (tool.name === "crewhelm_status") {
      documented.push({ operations: [], tool });
      continue;
    }

    const listed = operationListSchema.parse(
      await callTool(authority, requestId++, tool.name, { request: "operations" }),
    );
    const operationSummaries = listed.operations.map(
      ({ description }) => description.match(/^.*?[.!?](?:\s|$)/)?.[0].trim() ?? description,
    );
    expect(
      new Set(operationSummaries).size,
      `${tool.name} exposes distinct operation summaries`,
    ).toBe(operationSummaries.length);
    expect(operationSummaries, `${tool.name} exposes one-sentence operation summaries`).toEqual(
      listed.operations.map(({ description }) => description),
    );
    for (const operation of listed.operations) {
      const priorDescriptions =
        descriptionsByOperationName.get(operation.name) ?? new Set<string>();
      expect(
        priorDescriptions.has(operation.description),
        `${operation.name} has a facade-specific description`,
      ).toBe(false);
      priorDescriptions.add(operation.description);
      descriptionsByOperationName.set(operation.name, priorDescriptions);
      expect(
        operation.description.length,
        `${tool.name}.${operation.name} summary length`,
      ).toBeLessThanOrEqual(160);
    }
    const operations: DocumentedOperation[] = [];
    for (const operation of listed.operations) {
      const described = operationSchemaResultSchema.parse(
        await callTool(authority, requestId++, tool.name, {
          name: operation.name,
          request: "schema",
        }),
      );
      const serializedSchema = JSON.stringify(described.schema);
      expect(serializedSchema).not.toContain('"$ref"');
      expect(serializedSchema).not.toContain('"$defs"');
      expectConstructibleAuthoringInputs(described.schema, `${tool.name}.${operation.name}`);
      expect(
        new TextEncoder().encode(serializedSchema).byteLength,
        `${tool.name}.${operation.name} progressive schema bytes`,
      ).toBeLessThanOrEqual(MCP_PROGRESSIVE_OPERATION_SCHEMA_SIZE_BUDGET_BYTES);
      operations.push({
        description: operation.description,
        name: described.operation,
        schema: described.schema,
      });
    }
    documented.push({ operations, tool });
  }

  return documented;
}

describe("MCP documentation", () => {
  it("escapes Markdown delimiters in generated schema details", () => {
    expect(markdownText("token`value|next")).toBe("token`value\\|next");
    expect(markdownCodeSpan("token`value")).toBe("``token`value``");
  });

  it("matches the authenticated tool catalog", async () => {
    const authority = ownerAuthoritySchema.parse({
      clientId: "mcp-documentation",
      ownerKey: await deriveOwnerKey({
        issuer: "https://github.com",
        subject: "mcp-documentation",
      }),
      scopes: [OWNER_READ_SCOPE],
    });
    const response = await handleAuthenticatedMcpRequest(toolListRequest(), env, { authority });
    const payload = toolListResponseSchema.parse(await response.json());
    const tools = await discoverTools(authority, payload.result.tools);
    const expectedToolNames = [
      "crewhelm_status",
      ...FACADE_THEME_DEFINITIONS.flatMap(({ tools: themeDefinitions }) =>
        themeDefinitions.map(({ name }) => name),
      ),
    ].toSorted();
    expect(tools.map(({ tool }) => tool.name).toSorted()).toEqual(expectedToolNames);

    await expect(renderRepositoryOverview(tools)).toMatchFileSnapshot(
      "../../../../docs/reference/mcp/index.md",
    );
    await expect(renderSiteOverview(tools)).toMatchFileSnapshot(
      "../../../../apps/site/src/content/docs/docs/reference/mcp/index.md",
    );

    for (const theme of FACADE_THEME_DEFINITIONS) {
      await expect(renderRepositoryTheme(theme, tools)).toMatchFileSnapshot(
        `../../../../docs/reference/mcp/${theme.slug}.md`,
      );
      await expect(renderSiteTheme(theme, tools)).toMatchFileSnapshot(
        `../../../../apps/site/src/content/docs/docs/reference/mcp/${theme.slug}.md`,
      );
    }
  });
});
