import { env } from "cloudflare:test";
import { OWNER_READ_SCOPE, ownerAuthoritySchema } from "@crewhelm/contracts";
import { describe, expect, it } from "vitest";
import * as z from "zod";

import { deriveOwnerKey } from "../owner/identity.js";
import { MCP_GETTING_STARTED_REFERENCE } from "./guidance.js";
import { handleAuthenticatedMcpRequest } from "./server.js";

const origin = "https://crewhelm.test";
const toolListResponseSchema = z.looseObject({
  result: z.looseObject({
    tools: z.array(
      z.looseObject({
        annotations: z
          .looseObject({
            destructiveHint: z.boolean().optional(),
            idempotentHint: z.boolean().optional(),
            openWorldHint: z.boolean().optional(),
            readOnlyHint: z.boolean().optional(),
          })
          .optional(),
        description: z.string().optional(),
        inputSchema: z.record(z.string(), z.unknown()),
        name: z.string(),
        title: z.string().optional(),
      }),
    ),
  }),
});

type McpTool = z.infer<typeof toolListResponseSchema>["result"]["tools"][number];

const GENERATED_NOTICE = "<!-- Generated by `pnpm docs:mcp`. Do not edit manually. -->";

function annotationLabels(tool: McpTool): string[] {
  const annotations = tool.annotations;

  if (!annotations) {
    return [];
  }

  return [
    annotations.readOnlyHint ? "read-only" : "write",
    annotations.destructiveHint ? "destructive" : "non-destructive",
    annotations.idempotentHint ? "idempotent" : "non-idempotent",
    annotations.openWorldHint ? "open-world" : "closed-world",
  ];
}

function renderTool(tool: McpTool): string {
  const lines = [`## \`${tool.name}\``, ""];

  if (tool.title) {
    lines.push(`**${tool.title}**`, "");
  }

  if (tool.description) {
    lines.push(tool.description, "");
  }

  const labels = annotationLabels(tool);
  if (labels.length > 0) {
    lines.push(`Attributes: ${labels.join(", ")}.`, "");
  }

  lines.push(
    "<details>",
    "<summary>Input schema</summary>",
    "",
    "```json",
    JSON.stringify(tool.inputSchema, null, 2),
    "```",
    "",
    "</details>",
  );

  return lines.join("\n");
}

function renderReferenceBody(tools: McpTool[], includeTitle: boolean): string {
  const sections = tools
    .toSorted((left, right) => left.name.localeCompare(right.name))
    .map(renderTool);

  return [
    ...(includeTitle ? ["# MCP tool reference", ""] : []),
    "This reference is generated from Crewhelm's authenticated MCP `tools/list` response.",
    "Tool availability does not grant authority; every call is subject to the authenticated",
    "owner, approved OAuth scopes, and current control-plane policy.",
    "",
    MCP_GETTING_STARTED_REFERENCE,
    "",
    ...sections.flatMap((section) => [section, ""]),
  ].join("\n");
}

function renderRepositoryReference(tools: McpTool[]): string {
  return [GENERATED_NOTICE, "", renderReferenceBody(tools, true)].join("\n");
}

function renderSiteReference(tools: McpTool[]): string {
  return [
    "---",
    "title: MCP tool reference",
    "description: Exact generated inputs and annotations for Crewhelm's authenticated MCP tools.",
    "type: reference",
    "audience: mcp-client",
    "area: reference",
    "availability: available",
    "sources:",
    "  - apps/worker/src/mcp/documentation.test.ts",
    "  - apps/worker/src/mcp/server.ts",
    "tableOfContents: false",
    "---",
    "",
    GENERATED_NOTICE,
    "",
    renderReferenceBody(tools, false),
  ].join("\n");
}

function toolListRequest(): Request {
  return new Request(`${origin}/mcp`, {
    body: JSON.stringify({
      id: 1,
      jsonrpc: "2.0",
      method: "tools/list",
      params: {},
    }),
    headers: {
      accept: "application/json, text/event-stream",
      "content-type": "application/json",
      "mcp-protocol-version": "2025-11-25",
    },
    method: "POST",
  });
}

describe("MCP documentation", () => {
  it("matches the authenticated tool catalog", async () => {
    const authority = ownerAuthoritySchema.parse({
      clientId: "mcp-documentation",
      ownerKey: await deriveOwnerKey({
        issuer: "https://github.com",
        subject: "mcp-documentation",
      }),
      scopes: [OWNER_READ_SCOPE],
    });
    const response = await handleAuthenticatedMcpRequest(toolListRequest(), env, { authority });
    const payload = toolListResponseSchema.parse(await response.json());
    const repositoryReference = renderRepositoryReference(payload.result.tools);
    const siteReference = renderSiteReference(payload.result.tools);

    await expect(repositoryReference).toMatchFileSnapshot(
      "../../../../docs/reference/mcp-tools.md",
    );
    await expect(siteReference).toMatchFileSnapshot(
      "../../../../apps/site/src/content/docs/docs/reference/mcp-tools.md",
    );
  });
});
